name: ImmortalWrt-24.10 for N1
on:
  workflow_dispatch: # 只要保留这个，按钮就在
jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Please run this workflow on the 'Openwrt-24.10' branch."
